export type CameraData = {
  num: string;
  name: string;
  mpix: string;
  price: string;
  manufacturer: string;
  type: string;
  stabilization: string | string[];
  img: string;
  stock: boolean;
};

const data: CameraData[] = [
  {
    num: '1',
    name: 'Canon EOS 4000D 18-55 DC III',
    mpix: '18',
    price: '12899',
    manufacturer: 'Canon',
    type: 'DSLR',
    stabilization: 'optical',
    img: 'canon_eos_4000d_18-55_dc_iii_3011c004',
    stock: true,
  },
  {
    num: '2',
    name: 'Canon EOS 5D Mark IV 24-105L IS II',
    mpix: '30',
    price: '112999',
    manufacturer: 'Canon',
    type: 'DSLR',
    stabilization: ['optical', 'matrix'],
    img: 'canon_eos_5d_mark_iv_24-105l_is_ii_usm_kit_1483c030',
    stock: true,
  },
  {
    num: '3',
    name: 'Canon EOS 2000D 18-55 DC III',
    mpix: '24',
    price: '16899',
    manufacturer: 'Canon',
    type: 'DSLR',
    stabilization: 'optical',
    img: 'canon_eos_2000d_18-55_dc_iii_2728c007',
    stock: true,
  },
  {
    num: '4',
    name: 'Canon EOS 250D Kit 18-55 IS White',
    mpix: '24',
    price: '22999',
    manufacturer: 'Canon',
    type: 'DSLR',
    stabilization: 'optical',
    img: 'canon_eos_250d_kit_18-55_is_white_3458c003',
    stock: false,
  },
  {
    num: '5',
    name: 'Canon EOS 6D MK II Body',
    mpix: '27',
    price: '47160',
    manufacturer: 'Canon',
    type: 'DSLR',
    stabilization: 'optical',
    img: 'canon_eos_6d_mk_ii_body',
    stock: true,
  },
  {
    num: '6',
    name: 'Canon EOS 800D 18-55 IS STM Kit',
    mpix: '24',
    price: '29299',
    manufacturer: 'Canon',
    type: 'DSLR',
    stabilization: 'optical',
    img: 'canon_eos_800d_18-55_is_stm_kit_1895c019',
    stock: false,
  },
  {
    num: '7',
    name: 'Canon EOS C70 Cinema Camera',
    mpix: '9',
    price: '164988',
    manufacturer: 'Canon',
    type: 'mirrorless',
    stabilization: 'optical',
    img: 'canon_eos_c70_cinema_camera',
    stock: false,
  },
  {
    num: '8',
    name: 'Canon EOS M200 + 15-45 IS STM White',
    mpix: '24',
    price: '20999',
    manufacturer: 'Canon',
    type: 'compact',
    stabilization: 'optical',
    img: 'canon_eos_m200_+_15-45_is_stm_white_3700c032',
    stock: false,
  },
  {
    num: '9',
    name: 'Canon EOS M50 Mk2 + 15-45 IS STM + 55-200 IS',
    mpix: '24',
    price: '36399',
    manufacturer: 'Canon',
    type: 'DSLR',
    stabilization: 'optical',
    img: 'canon_eos_m50_mk2_+_15-45_is_stm_kit_white_4729c028',
    stock: false,
  },
  {
    num: '10',
    name: 'Canon EOS M6 Mark II + 15-45 IS STM + EVF Kit',
    mpix: '34',
    price: '40199',
    manufacturer: 'Canon',
    type: 'mirrorless',
    stabilization: 'optical',
    img: 'canon_eos_m6_mark_ii_+_15-45_is_stm_+_evf_kit_black_3611c053',
    stock: false,
  },
  {
    num: '11',
    name: 'Canon Zoemini S ZV123 Mbk',
    mpix: '8',
    price: '6427',
    manufacturer: 'Canon',
    type: 'compact',
    stabilization: 'none',
    img: 'canon_zoemini_s_zv123_mbk',
    stock: false,
  },
  {
    num: '12',
    name: 'Canon Powershot G5 X Mark II Black',
    mpix: '20',
    price: '33999',
    manufacturer: 'Canon',
    type: 'compact',
    stabilization: 'optical',
    img: 'canon_powershot_g5_x_mark_ii_black_3070c013',
    stock: false,
  },
  {
    num: '13',
    name: 'Canon PowerShot SX540 HS Black',
    mpix: '20',
    price: '12399',
    manufacturer: 'Canon',
    type: 'ultrazoom',
    stabilization: 'optical',
    img: 'canon_powershot_sx540_hs_black_1067c012',
    stock: true,
  },
  {
    num: '14',
    name: 'Canon PowerShot Zoom',
    mpix: '12',
    price: '12199',
    manufacturer: 'Canon',
    type: 'ultrazoom',
    stabilization: 'optical',
    img: 'canon_powershot_zoom_4838c007',
    stock: true,
  },
  {
    num: '15',
    name: 'Fujifilm Instax Mini 90 Brown EX D',
    mpix: '2',
    price: '4999',
    manufacturer: 'Fujifilm',
    type: 'compact',
    stabilization: 'none',
    img: 'fujifilm_instax_mini_90_brown_ex_d_16423981',
    stock: false,
  },
  {
    num: '16',
    name: 'Fujifilm Instax Mini LiPlay Blush Gold',
    mpix: '5',
    price: '5999',
    manufacturer: 'Fujifilm',
    type: 'compact',
    stabilization: 'none',
    img: 'fujifilm_instax_mini_liplay_blush_gold_16631849',
    stock: true,
  },
  {
    num: '17',
    name: 'Fujifilm X-S10+ XF 16-80mm F4.0 Kit Black',
    mpix: '26',
    price: '57339',
    manufacturer: 'Fujifilm',
    type: 'mirrorless',
    stabilization: 'matrix',
    img: 'fujifilm_x-s10+_xf_16-80mm_f4_0_kit_black_16670077',
    stock: true,
  },
  {
    num: '18',
    name: 'Fujifilm X-T30 II Mirrorless Digital Camera',
    mpix: '26',
    price: '32400',
    manufacturer: 'Fujifilm',
    type: 'mirrorless',
    stabilization: 'optical',
    img: 'fujifilm_x-s10+_xf_16-80mm_f4_0_kit_black_16670077',
    stock: false,
  },
  {
    num: '19',
    name: 'Fujifilm X-T4 Body Black',
    mpix: '26',
    price: '64659',
    manufacturer: 'Fujifilm',
    type: 'mirrorless',
    stabilization: 'matrix',
    img: 'fujifilm_x-t4_body_black_16650467',
    stock: true,
  },
  {
    num: '20',
    name: 'Nikon D3500 + AF-P 18-55 Non VR',
    mpix: '24',
    price: '18256',
    manufacturer: 'Nikon',
    type: 'DSLR',
    stabilization: 'none',
    img: 'nikon_d3500_+_af-p_18-55_non_vr_vba550k002',
    stock: true,
  },
  {
    num: '21',
    name: 'Nikon D5600 Kit AF-P 18-55 VR',
    mpix: '24',
    price: '25499',
    manufacturer: 'Nikon',
    type: 'DSLR',
    stabilization: 'optical',
    img: 'nikon_d5600_kit_af-p_18-55_vr_vba500k001',
    stock: true,
  },
  {
    num: '22',
    name: 'Nikon Z fc + 16-50 VR Kit',
    mpix: '21',
    price: '34399',
    manufacturer: 'Nikon',
    type: 'mirrorless',
    stabilization: 'optical',
    img: 'nikon_z_fc_+_16-50_vr_kit_voa090k002',
    stock: false,
  },
  {
    num: '23',
    name: 'Nikon Z7 24-70 f4 Kit',
    mpix: '46',
    price: '116999',
    manufacturer: 'Nikon',
    type: 'mirrorless',
    stabilization: 'matrix',
    img: 'nikon_z7_24-70_f4_kit_voa010k001',
    stock: false,
  },
  {
    num: '24',
    name: 'Nikon D5-b Body (CF)',
    mpix: '21',
    price: '140399',
    manufacturer: 'Nikon',
    type: 'DSLR',
    stabilization: 'matrix',
    img: 'nikon_d5-b_body_cf_vba460be',
    stock: false,
  },
  {
    num: '25',
    name: 'Panasonic LUMIX DC-FZ82EE-K Black',
    mpix: '18',
    price: '10999',
    manufacturer: 'Panasonic',
    type: 'ultrazoom',
    stabilization: 'optical',
    img: 'panasonic_lumix_dc-fz82ee-k_black',
    stock: false,
  },
  {
    num: '26',
    name: 'Panasonic LUMIX DC-FZ10002EE',
    mpix: '21',
    price: '22999',
    manufacturer: 'Panasonic',
    type: 'compact',
    stabilization: 'optical',
    img: 'panasonic_lumix_dc-fz10002ee',
    stock: false,
  },
  {
    num: '27',
    name: 'Panasonic LUMIX DC-G90MEE-K Kit 12-60mm',
    mpix: '21',
    price: '30999',
    manufacturer: 'Panasonic',
    type: 'mirrorless',
    stabilization: 'optical',
    img: 'panasonic_lumix_dc-g90mee-k_kit_12-60mm_black',
    stock: true,
  },
  {
    num: '28',
    name: 'Panasonic LUMIX DC-TZ200EE-K Black',
    mpix: '20',
    price: '21999',
    manufacturer: 'Panasonic',
    type: 'compact',
    stabilization: 'optical',
    img: 'panasonic_lumix_dc-tz200ee-k_black',
    stock: true,
  },
  {
    num: '29',
    name: 'Panasonic LUMIX DMC-FT30EE-A Blue',
    mpix: '16',
    price: '7499',
    manufacturer: 'Panasonic',
    type: 'compact',
    stabilization: 'none',
    img: 'panasonic_lumix_dmc-ft30ee-a_blue',
    stock: true,
  },
  {
    num: '30',
    name: 'Panasonic LUMIX DMC-LX15EEK',
    mpix: '20',
    price: '16999',
    manufacturer: 'Panasonic',
    type: 'compact',
    stabilization: 'optical',
    img: 'panasonic_lumix_dmc-lx15eek',
    stock: true,
  },
  {
    num: '31',
    name: 'Panasonic LUMIX DMC-TZ100EEK',
    mpix: '20',
    price: '15999',
    manufacturer: 'Panasonic',
    type: 'compact',
    stabilization: 'optical',
    img: 'panasonic_lumix_dmc-tz100eek',
    stock: false,
  },
  {
    num: '32',
    name: 'Sony Alpha 7M4 28-70mm Kit Black',
    mpix: '21',
    price: '30999',
    manufacturer: 'Sony',
    type: 'mirrorless',
    stabilization: 'optical',
    img: 'sony_alpha_7m4_28-70mm_kit_black_ilce7m4kb_cec',
    stock: false,
  },
  {
    num: '33',
    name: 'Sony Alpha 9M2 Body Black',
    mpix: '28',
    price: '149999',
    manufacturer: 'Sony',
    type: 'mirrorless',
    stabilization: 'optical',
    img: 'sony_alpha_9m2_body_black_ilce9m2b_cec',
    stock: true,
  },
  {
    num: '34',
    name: 'Sony Cyber-Shot H300 Black',
    mpix: '20',
    price: '7999',
    manufacturer: 'Sony',
    type: 'ultrazoom',
    stabilization: 'optical',
    img: 'sony_cyber-shot_h300_black_dsch300_ru3',
    stock: false,
  },
  {
    num: '35',
    name: 'Sony Cyber-Shot RX10 MkIV',
    mpix: '21',
    price: '59999',
    manufacturer: 'Sony',
    type: 'compact',
    stabilization: 'optical',
    img: 'sony_cyber-shot_rx10_mkiv_dscrx10m4_ru3',
    stock: true,
  },
  {
    num: '36',
    name: 'Sony Cyber-Shot RX100 MkVA Black',
    mpix: '20',
    price: '33999',
    manufacturer: 'Sony',
    type: 'compact',
    stabilization: 'optical',
    img: 'sony_cyber-shot_rx100_mkva_black_dscrx100m5a_ru3',
    stock: false,
  },
];

export default data;
